server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  application:
    name: todo

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect